# PATH
# ============================================================================= 

# on some computers, nvim is in /opt:
if [[ -e /opt/nvim/bin/nvim ]]
then
    path=(/opt/nvim/bin $path)
fi

path=(~/.local/bin ~/.cargo/bin $path)

# POWERLEVEL10K
# ============================================================================= 

source ~/.config/zsh/powerlevel10k/powerlevel10k.zsh-theme
source ~/.config/zsh/zshrc.powerlevel10k

# Aliases
# ============================================================================= 

if command -v eza > /dev/null; then
	alias ls='eza --icons --group-directories-first'
	alias ll='eza -alh --group-directories-first'
	alias l='eza -lh --group-directories-first'
	alias tree='eza --tree --group-directories-first'
else
	alias ls='ls --color'
	alias ll='ls -alh'
	alias l='ls -lh'
fi

if command -v bat > /dev/null; then
	alias cat='bat'
	export BAT_THEME=zenburn
elif command -v batcat > /dev/null; then
	alias cat='batcat'
fi

if command -v nvim > /dev/null; then
	alias vi='nvim'
  export EDITOR=$(command -v nvim)
fi

alias gls='git status'
alias grep='grep --color=auto'

if command -v kitten > /dev/null; then
    alias icat='kitten icat'
fi

if [[ -f /Library/Frameworks/R.framework/Resources/library/rush/exec/rush ]]
then
    alias rush='/Library/Frameworks/R.framework/Resources/library/rush/exec/rush'
elif [[ -f ~/R/x86_64-pc-linux-gnu-library/4.3/rush/exec/rush ]]
then
    alias rush='~/R/x86_64-pc-linux-gnu-library/4.3/rush/exec/rush'
fi

if command -v qutebrowser > /dev/null; then
    alias cube='qutebrowser'
fi

# Use rbw (bitwarden cli) for sudo and ssh passwords
# =============================================================================

if command -v rbw > /dev/null; then
    # sudo -A will use bitwarden to look up password based on username
    # sudo asks for and host the command is executed on:
    export SUDO_ASKPASS="${HOME}/.local/bin/askpass_sudo"

    export SSH_ASKPASS="${HOME}/.local/bin/askpass_ssh"
    export SSH_ASKPASS_REQUIRE=force

    # also configure rbw-menu (separate tool) to use fzf:
    export RBW_MENU_COMMAND='fzf --prompt "$query: "'

    alias ru='rbw unlock'
fi

# MOSH
# =============================================================================

# fixes locale problem on MacOS:
if [[ "$OSTYPE" == "darwin"* ]]
then
	export LANG=en_US.UTF-8
	export LC_CTYPE=en_US.UTF-8
fi

# AI Keys for mods and mcp-servers:
#==============================================================================

[[ -f ~/.OPENAI_API_KEY ]] && export OPENAI_API_KEY=$(cat ~/.OPENAI_API_KEY)
[[ -f ~/.XAI_API_KEY ]] && export XAI_API_KEY=$(cat ~/.XAI_API_KEY)
[[ -f ~/.BRAVE_API_KEY ]] && export BRAVE_API_KEY=$(cat ~/.BRAVE_API_KEY)

# HISTORY
# ============================================================================= 

# share history accross multiple zsh sessions:
setopt SHARE_HISTORY

# append to history:
setopt APPEND_HISTORY

# remove blank lines from history:
setopt HIST_REDUCE_BLANKS

HISTFILE=${ZDOTDIR:-$HOME}/.zsh_history
SAVEHIST=5000
HISTSIZE=2000

# completions
# =============================================================================

autoload -Uz compinit
compinit
_comp_options+=(globdots)
# group names in bold:
zstyle ':completion:*:descriptions' format '[%d]'
# show menu select on double-tab:
zstyle ':completion:*' menu select=0
# group completions (e.g., "external command", "builtin command" ...):
zstyle ':completion:*' group-name ''

# configure vi-like navigation in completion menu:
zmodload zsh/complist
bindkey -M menuselect 'h' vi-backward-char
bindkey -M menuselect 'k' vi-up-line-or-history
bindkey -M menuselect 'j' vi-down-line-or-history
bindkey -M menuselect 'l' vi-forward-char

# configure fzf selection in menu:
source ~/.config/zsh/fzf-tab/fzf-tab.plugin.zsh
# disable sort when completing `git checkout`
zstyle ':completion:*:git-checkout:*' sort false
# set descriptions format to enable group support
# NOTE: don't use escape sequences (like '%F{red}%d%f') here,
# fzf-tab will ignore them
zstyle ':completion:*:descriptions' format '[%d]'
# set list-colors to enable filename colorizing
zstyle ':completion:*' list-colors ${(s.:.)LS_COLORS}
# force zsh not to show completion menu, which allows fzf-tab to capture
# the unambiguous prefix
zstyle ':completion:*' menu no
# preview directory's content with eza when completing cd
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'eza -1 --color=always $realpath'
# custom fzf flags
# NOTE: fzf-tab does not follow FZF_DEFAULT_OPTS by default
zstyle ':fzf-tab:*' fzf-flags --color=fg:1,fg+:2 --bind=tab:accept
# To make fzf-tab follow FZF_DEFAULT_OPTS.
# NOTE: This may lead to unexpected behavior since some flags break this
# plugin. See Aloxaf/fzf-tab#455.
zstyle ':fzf-tab:*' use-fzf-default-opts yes
# switch group using `<` and `>`
zstyle ':fzf-tab:*' switch-group '<' '>'

# completions for otherwise unsupported tools:
source ~/.config/zsh/completion/timewarrior.zsh
source ~/.config/zsh/completion/rbw.zsh

# zoxide
# =============================================================================

if command -v zoxide > /dev/null; then
	eval "$(zoxide init zsh)"
	if whence -w cd | grep 'alias' > /dev/null; then
		unalias cd > /dev/null
	fi
	alias cd='z'
fi

# timew
# =============================================================================

# 'timew-tagrename <oldtag> <newtag> <fromdate> <todate>
function timew-tagrename()
{
	local oldtag=$1; shift
	local newtag=$1; shift
    local from=$1; shift
    local to=$1; shift
	local idlist=$(timew summary $from - $to "$oldtag" :ids |\
	               sed -nr 's/.* (@[0-9]+) .*/\1/p')
	echo "$idlist" | xargs -I ids timew tag ids "$newtag"
	echo "$idlist" | xargs -I ids timew untag ids "$oldtag"
}

# vi mode
# =============================================================================

# switch zsh to vi-mode
bindkey -v

# but keep certain shortcuts from emacs-mode:
# (these are so hard-wired in muscle memory, I just can't work without):
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^F" forward-char
bindkey "^B" backward-char
bindkey "^K" kill-line
bindkey "^D" delete-char
bindkey "^P" history-beginning-search-backward
bindkey "^N" history-beginning-search-forward
bindkey "^R" history-incremental-search-backward

# and make backspace behave properly:
bindkey "^?" backward-delete-char

# make Esc delay shorter (otherwise it feels laggy):
export KEYTIMEOUT=1

# add command-line editing feature and shortcut:
autoload edit-command-line
zle -N edit-command-line
bindkey '^Xe' edit-command-line

# fzf
# =============================================================================

# (note: must be after activation of vi mode, otherwise fzf installs
# keybindings into emacs mode)

if [[ -f ~/.fzf/bin/fzf ]]
then
    path=(~/.fzf/bin $path)
fi

if command -v fzf > /dev/null
then
    source <(fzf --zsh)
fi

# nettools
# =============================================================================

source ~/.config/zsh/tools/nettools.rc

# colored man pages:
# (learned from @yousuckatprogramming who got it from https://grml.org)
# =============================================================================

# less (the pager) allows overriding terminal capabilities via a set of
# environment variables. We use this to change styles. E.g., instead of sending
# the sequence for double-bright mode, we send the sequence for bold red.
# Then, we make sure man is using less as its pager.
# Of course, these style changes apply to less in general, not only when it is
# used to show man-pages.

# Note: Compared to @yousuckatprogramming, I dropped those "overrides" that
# replaced a formatting sequence with the same it already was.

# blinking mode = bold red:
export LESS_TERMCAP_mb=$(tput bold; tput setaf 1)
# double-bright mode = bold red:
export LESS_TERMCAP_md=$(tput bold; tput setaf 1)
# stand-out mode = bold yellow on blue:
export LESS_TERMCAP_so=$(tput bold; tput setaf 3; tput setab 4)
# leave stand-out mode = turn-off all appearance modes:
export LESS_TERMCAP_se=$(tput sgr0)
# underline mode = underline bold green:
export LESS_TERMCAP_us=$(tput smul; tput bold; tput setaf 2)
# leave underline mode = turn-off all appearance modes:
export LESS_TERMCAP_ue=$(tput sgr0)

# use less to show man-pages:
export MANPAGER='less'

# catppuccin syntax-highlighting theme
# (must be last in this config file)
# ============================================================================= 

source ~/.config/zsh/catppuccin/themes/catppuccin_macchiato-zsh-syntax-highlighting.zsh
source ~/.config/zsh/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

