nerdfont: true
worktree_dir: .worktrees
merge_strategy: rebase
agent: crush
agents:
  crush:
    command: pi
    type: pi

panes:
  - command: <agent>
    focus: true
  - split: horizontal
    command: "vi"
  - split: vertical
